name:  CI/CD

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: install dependencies
        run: npm ci
      - name: run linter
        run: npm run eslint

      # Mongo is needed for running tests
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4.2
      - name: test
        run: npm run test

  publish:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build image and push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: ghcr.io
          repository: giveth/feathers-giveth
          add_git_labels: true
          # Add branch name to docker image tag @see{@link https://github.com/docker/build-push-action/tree/releases/v1#tag_with_ref}
          tag_with_ref: true
          # Add commit hash to docker image tag @see{@link https://github.com/docker/build-push-action/tree/releases/v1#tag_with_sha}
          tag_with_sha: true

  deploy:
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master'
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: develop deploy
        if: github.ref == 'refs/heads/develop'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
#          command: cd feathers-giveth-develop && git checkout develop && git pull origin develop && [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh && nvm use 10  && npm ci &&  NODE_ENV=develop ./node_modules/.bin/migrate-mongo up && npm run serve
          #           pull images, restart docker, then remove unused docker images
          command: cd feathers-giveth-develop && git checkout develop && git pull origin develop && git pull origin develop && docker-compose -f docker-compose-develop.yml pull && docker-compose -f docker-compose-develop.yml down && docker-compose -f docker-compose-develop.yml up -d && docker image prune -a --force
          host: ${{ secrets.DEVELOP_HOST }}
          username: ${{ secrets.DEVELOP_USERNAME }}
          #          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.DEVELOP_PRIVATE_KEY}}

      - name: beta deploy
        if: github.ref == 'refs/heads/master'
        uses: garygrossgarten/github-action-ssh@v0.6.4
        with:
#          command: cd feathers-giveth-beta && git checkout master && git pull origin master && [[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh && nvm use 10  && npm ci &&  NODE_ENV=production ./node_modules/.bin/migrate-mongo up && npm run serve
          # pull images, restart docker, then remove unused docker images
          command: cd feathers-giveth-beta && git checkout master && git pull origin master && docker-compose -f docker-compose-production.yml pull && docker-compose -f docker-compose-production.yml down && docker-compose -f docker-compose-production.yml up -d && docker image prune -a --force
          host: ${{ secrets.BETA_HOST }}
          username: ${{ secrets.BETA_USERNAME }}
          #          passphrase: ${{ secrets.PASSPHRASE }}
          privateKey: ${{ secrets.BETA_PRIVATE_KEY}}
